theme: jekyll-theme-minimal
title: Joes Page
logo: Pic.png
description: >
  Hi! I'm Joseph Daly, I'm a student at St Mary's College of Maryland studying Mathematics and pursuing a minor in Business and Philosophy<br/>
  <a href="mailto:jtdaly@smcm.edu">Email</a> | <a href="www.linkedin.com/in/joecontrair">LinkedIn</a>
