theme: jekyll-theme-minimal
title: Joes Page
logo: Pic.png
description: >
  Hi! I'm Joseph Daly, I'm a student at St Mary's College of Maryland studying Mathematics and pursuing a minor in Business and Philosophy 
  [Email](mailto:jtdaly@smcm.edu) | [Linked.in](www.linkedin.com/in/joecontrair)
