theme: jekyll-theme-minimal
title: Joes Page
logo: https://media-exp1.licdn.com/dms/image/C4D03AQE4i3bwQ1Rhow/profile-displayphoto-shrink_400_400/0/1643730881008?e=1651104000&v=beta&t=7aX6lo40ZLNCAuZojfivPVzPtFsa5mnaxP6x4l1u0g8 
description: A personal webapage for all of my projects 
