theme: jekyll-theme-minimal
title: Personal website
markdown: kramdown
logo: Personal/assets/Images/Joecool.png
author: Joe Daly
style: Comic Sans MS
description: 
  Undergraduate studying Mathematics at St Marys College of Maryland <br/>
  <a href="mailto:jtdaly@smcm.edu">Email</a> | <a href="https://www.linkedin.com/in/joecontrair/">LinkedIn</a> | <a href="https://www.instagram.com/thedalyjoe/">Instagram</a>

