theme: jekyll-theme-minimal
title: Joseph Daly
logo: Pic.png
description: >
  Hi! I'm Joseph Daly, I'm a student at St Mary's College of Maryland studying Mathematics and pursuing a minor in Business and Philosophy<br/>
  <a href="mailto:jtdaly@smcm.edu">Email</a> | [LinkedIn](www.linkedin.com/in/joecontrair) | <a href="https://www.instagram.com/thedalyjoe/">Instagram</a>
