theme: jekyll-theme-minimal
title: Personal Sight
logo: assets/Images/Pic.png
author: Joe Daly
description: >
  Undergraduate studying Mathematics at St Marys College of Maryland <br/>
  <a href="mailto:jtdaly@smcm.edu">Email</a> | <a href="https://www.linkedin.com/in/joecontrair/">LinkedIn</a> | <a href="https://www.instagram.com/thedalyjoe/">Instagram</a>

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      related: true
