theme: jekyll-theme-minimal
title: Personal website
logo: assets/Images/Joecool.png
author: Joe Daly
<script src="https://utteranc.es/client.js"
        repo=" Joecontrair / Joecontrair.github.io "
        issue-term="pathname"
        label="Comment"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>
description: >
  Undergraduate studying Mathematics at St Marys College of Maryland <br/>
  <a href="mailto:jtdaly@smcm.edu">Email</a> | <a href="https://www.linkedin.com/in/joecontrair/">LinkedIn</a> | <a href="https://www.instagram.com/thedalyjoe/">Instagram</a>

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      related: true
